import { useMemo, useState } from "react";
import { trpc } from "@/lib/trpc";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { RefreshCw, ArrowUpRight, Download, Send, ShieldCheck, Database, Activity, AlertTriangle, Command, Radio } from "lucide-react";

const suggestions = ["What's our pipeline value in mining?", "How many deals have we won?", "How healthy are work orders?", "Which deals converted into active work orders?"];

function MetricCard({ label, value, caption, tone = "blue" }: { label: string; value: string; caption: string; tone?: "blue" | "green" | "amber" }) {
  return <article className="metric-card blueprint-frame">
    <div className="flex items-center justify-between"><span className="eyebrow">{label}</span><span className={`metric-dot ${tone}`} /></div>
    <div className="metric-value">{value}</div>
    <p className="metric-caption">{caption}</p>
  </article>;
}

function SourceList({ sources }: { sources?: Array<{ itemName: string; field?: string; url: string }> }) {
  if (!sources?.length) return null;
  return <details className="source-details"><summary>Evidence · {sources.length} source items</summary><div className="source-list">{sources.slice(0, 8).map((source, index) => <a key={`${source.url}-${index}`} href={source.url} target="_blank" rel="noreferrer"><span>{String(index + 1).padStart(2, "0")}</span><span>{source.itemName}</span><small>{source.field ?? "item"}</small><ArrowUpRight size={13} /></a>)}</div></details>;
}

export default function Home() {
  const snapshot = trpc.bi.snapshot.useQuery(undefined, { refetchOnWindowFocus: false });
  const refresh = trpc.bi.refresh.useMutation({ onSuccess: () => snapshot.refetch() });
  const ask = trpc.bi.ask.useMutation();
  const update = trpc.bi.leadershipUpdate.useQuery(undefined, { enabled: false });
  const [question, setQuestion] = useState("");
  const state = snapshot.data?.state;
  const quality = state?.quality;
  const modeLabel = state?.mode === "live" ? "LIVE MONDAY.COM" : state?.mode === "cached" ? "CACHED SNAPSHOT" : "DEMO DATA";
  const qualityScore = useMemo(() => quality ? Math.max(0, Math.round(100 - ((quality.deals?.missing?.closeDate ?? 0) + (quality.workOrders?.missing?.status ?? 0) + quality.invalidDates) / Math.max(1, quality.totalRows) * 100)) : 0, [quality]);

  const submitQuestion = (value = question) => { if (!value.trim() || ask.isPending) return; ask.mutate({ question: value.trim() }); setQuestion(""); };
  const downloadUpdate = async () => { const result = await update.refetch(); if (!result.data?.markdown) return; const blob = new Blob([result.data.markdown], { type: "text/markdown;charset=utf-8" }); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = "skylark-leadership-update.md"; anchor.click(); URL.revokeObjectURL(url); };

  return <div className="app-shell">
    <aside className="side-rail">
      <div className="brand-mark"><div className="brand-sigil"><span /><span /><span /></div><div><strong>SKYLARK</strong><small>BI AGENT / 01</small></div></div>
      <nav className="rail-nav"><a className="active" href="#overview"><Activity size={16} />Overview</a><a href="#evidence"><ShieldCheck size={16} />Evidence ledger</a><a href="#questions"><Command size={16} />Ask the agent</a><a href="#notes"><Database size={16} />Decision log</a></nav>
      <div className="rail-bottom"><div className="rail-coordinate">BOARDS LINKED: 02<br />ROWS SYNCED: {quality?.totalRows ?? "—"}</div><div className="rail-status"><span className="live-pulse" />{state?.mode === "live" ? "Live sync active" : state?.mode === "cached" ? "Using cached data" : "Demo mode"}</div></div>
    </aside>
    <main className="main-canvas">
      <header className="topbar"><div><div className="breadcrumb">SKYLARK / INTELLIGENCE CONSOLE</div><h1>Operating picture</h1></div><div className="top-actions"><div className={`data-status ${state?.mode ?? "loading"}`}><span className="status-dot" />{state ? modeLabel : "CONNECTING"}<small>{state ? new Date(state.fetchedAt).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" }) : "—"}</small></div><Button className="refresh-button" onClick={() => refresh.mutate()} disabled={refresh.isPending}><RefreshCw size={15} className={refresh.isPending ? "spin" : ""} />Refresh data</Button></div></header>{state?.error && <div className="sync-notice"><AlertTriangle size={14} />{state.error}</div>}
      <section className="hero-strip blueprint-frame" id="overview"><div><span className="eyebrow accent">MISSION CONTROL / TRUST LAYER</span><h2>Turn board activity into<br /><em>decisions you can defend.</em></h2><p>Deterministic metrics, explicit caveats, and monday.com evidence references — built for the operating review.</p></div><div className="hero-annotation"><span>SYNC INTERVAL</span><strong>05:00</strong><span>BOARDS LINKED</span><strong>02 / 02</strong><span>QUALITY SCORE</span><strong>{qualityScore}%</strong></div><div className="dimension-line"><span>ARCHITECTURAL BLUEPRINT / 2026</span><i /><span>REV. 01</span></div></section>
      <section className="metric-grid"> <MetricCard label="Total pipeline" value={snapshot.data?.pipeline.headline ?? "—"} caption={snapshot.data?.pipeline.insight ?? "Loading normalized records"} /><MetricCard label="Work-order health" value={snapshot.data?.completion.headline ?? "—"} caption={snapshot.data?.completion.insight ?? "Loading operational status"} tone="green" /><MetricCard label="Deal conversion" value={snapshot.data?.conversion.headline ?? "—"} caption={snapshot.data?.conversion.insight ?? "Cross-board match rate"} tone="amber" /><MetricCard label="Stage distribution" value={snapshot.data?.stageBreakdown.headline ?? "—"} caption="Calculated from source-linked deal items" /></section>
      <section className="content-grid" id="questions"><div className="panel blueprint-frame agent-panel"><div className="panel-header"><div><span className="eyebrow">NATURAL-LANGUAGE QUERY</span><h3>Ask the operating picture</h3></div><Badge variant="outline"><Radio size={12} /> Planner → aggregate → narrate</Badge></div><div className="question-body"><div className="suggestion-row">{suggestions.map(s => <button key={s} onClick={() => submitQuestion(s)}>{s}</button>)}</div><div className="query-input"><input value={question} onChange={e => setQuestion(e.target.value)} onKeyDown={e => e.key === "Enter" && submitQuestion()} placeholder="Ask a founder question…" /><button onClick={() => submitQuestion()} aria-label="Submit question"><Send size={17} /></button></div>{ask.data?.clarificationNeeded && <div className="clarify-box"><AlertTriangle size={16} /><div><strong>One clarification before I calculate</strong><p>{ask.data.clarificationNeeded}</p></div></div>}{ask.data?.result && <div className="answer-card"><div className="answer-top"><div><span className="eyebrow">VERIFIED ANSWER / {ask.data.plan.metric.toUpperCase()}</span><h4>{ask.data.result.headline}</h4></div><Badge className="quality-badge"><ShieldCheck size={12} /> Source-backed</Badge></div><p className="narrative">{ask.data.result.narrative}</p><p className="answer-supporting">{ask.data.result.insight}</p>{ask.data.result.caveats.length > 0 && <div className="caveat"><AlertTriangle size={14} /><span>{ask.data.result.caveats.join(" ")}</span></div>}<SourceList sources={ask.data.result.sources} /></div>}{ask.isPending && <div className="loading-line"><span />Planner is mapping your question to fields…</div>}</div></div>
        <div className="panel blueprint-frame evidence-panel" id="evidence"><div className="panel-header"><div><span className="eyebrow">DATA QUALITY / TRACEABILITY</span><h3>Evidence ledger</h3></div><span className="ledger-count">{quality?.totalRows ?? "—"} rows</span></div><div className="quality-meter"><div className="meter-label"><span>Completeness signal</span><strong>{qualityScore}%</strong></div><div className="meter-track"><div style={{ width: `${qualityScore}%` }} /></div></div><div className="quality-list"><div><span className="quality-icon good"><ShieldCheck size={14} /></span><div><strong>Normalization pass</strong><small>Canonical sector labels retained in mapping</small></div><b>{quality?.normalizedLabels ?? 0}</b></div><div><span className="quality-icon warn"><AlertTriangle size={14} /></span><div><strong>Invalid dates</strong><small>Logged, never silently dropped</small></div><b>{quality?.invalidDates ?? 0}</b></div><div className="quality-board-split"><div className="eyebrow">DEALS ({quality?.deals?.total ?? 0} rows)</div><div className="quality-items">{Object.entries(quality?.deals?.missing ?? {}).map(([field, count]) => <div key={`deals-${field}`}><span className="quality-icon"><Database size={14} /></span><div><strong>Missing {field}</strong><small>{count} of {quality?.deals?.total ?? 0}</small></div><b>{count}</b></div>)}</div></div><div className="quality-board-split"><div className="eyebrow">WORK ORDERS ({quality?.workOrders?.total ?? 0} rows)</div><div className="quality-items">{Object.entries(quality?.workOrders?.missing ?? {}).map(([field, count]) => <div key={`wo-${field}`}><span className="quality-icon"><Database size={14} /></span><div><strong>Missing {field}</strong><small>{count} of {quality?.workOrders?.total ?? 0}</small></div><b>{count}</b></div>)}</div></div><div><span className="quality-icon"><Database size={14} /></span><div><strong>Likely duplicates</strong><small>Flagged for review, not auto-merged</small></div><b>{quality?.duplicateFlags ?? 0}</b></div></div><div className="quality-notes">{quality?.notes.map(note => <p key={note}>// {note}</p>)}</div></div></section>
      <section className="bottom-grid" id="notes"><div className="panel blueprint-frame update-panel"><div><span className="eyebrow accent">BOARD-READY OUTPUT</span><h3>Leadership update</h3><p>A deterministic one-pager with validated KPIs, operating risks, and data caveats.</p></div><Button onClick={downloadUpdate} disabled={update.isFetching}><Download size={15} />{update.isFetching ? "Generating…" : "Download Markdown"}</Button></div><div className="board-assumptions"><span className="eyebrow">LINKED SOURCES</span><strong>Deals <i>5030963379</i></strong><strong>Work Orders <i>5030963548</i></strong><small>Server-side token placeholder · read-only GraphQL sync</small></div></section>
      <footer><span>SKYLARK BI AGENT / TRUSTED OPERATIONS INTELLIGENCE</span><span>PUBLIC EVALUATOR VIEW · NO LOGIN REQUIRED</span></footer>
    </main>
  </div>;
}
